### ISSUE TITLE
Postgres: Cannot open table with uppercase characters in the name 

### ISSUE THREAD

**Issue by sgarg7** [saulpw/vdibis#30]
eg. if the table name is `transactionHistory`, the error is

```
UndefinedTable: relation "public.transactionhistory" does not exist·LINE 1
```

I am shown the table names with the right casing on the first screen but it can only open the table names that are only in lowercase.
Maybe there's something missing in my setup

Also, love visidata, thank you🙏

**Comment by anjakefala** [comment]
Hey @sgarg7!

The repo has been moved to https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql. We have recently pushed lots of fixes to the develop branch. Could you try installing vdsql from there, and seeing if this fixes your problems?
